spring:
  application:
    name: dacloud PGW

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3301/dacloud_pgw_be
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 6060

springdoc:
  api-docs:
    path: /api-doc
  swagger-ui:
    path: /api-doc.html
